# -*- coding: utf-8 -*-
"""init_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUzHdn1_jlMmJYvb0KAagsw1sVPmJpGs
"""

# init_db.py
import sqlite3
from datetime import datetime

DB_PATH = "geotax360.db"

def init_db(db_path: str = DB_PATH):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.executescript("""
    CREATE TABLE IF NOT EXISTS citizens (
      owner_id INTEGER PRIMARY KEY,
      full_name TEXT NOT NULL,
      nat_id TEXT,
      phone TEXT, email TEXT,
      address TEXT, created_at TEXT
    );

    CREATE TABLE IF NOT EXISTS parcels (
      parcel_id TEXT PRIMARY KEY,
      pluscode TEXT,
      ward TEXT, zone TEXT, neighborhood TEXT,
      owner_id INTEGER REFERENCES citizens(owner_id),
      geom_wkt TEXT
    );

    CREATE TABLE IF NOT EXISTS assessments (
      assessment_id INTEGER PRIMARY KEY,
      parcel_id TEXT REFERENCES parcels(parcel_id),
      method TEXT,
      avm_value_usd REAL,
      assessed_at TEXT
    );

    CREATE TABLE IF NOT EXISTS tax_bills (
      bill_id INTEGER PRIMARY KEY,
      parcel_id TEXT REFERENCES parcels(parcel_id),
      period TEXT, rate_code TEXT,
      amount_due REAL, status TEXT,
      issued_at TEXT, due_at TEXT
    );

    CREATE TABLE IF NOT EXISTS payments (
      payment_id INTEGER PRIMARY KEY,
      bill_id INTEGER REFERENCES tax_bills(bill_id),
      paid_at TEXT, amount REAL, channel TEXT
    );
    """)

    # Seed only if empty
    cur.execute("SELECT COUNT(*) FROM citizens")
    if cur.fetchone()[0] == 0:
        now = datetime.utcnow().strftime("%Y-%m-%d")

        cur.execute("""INSERT INTO citizens(full_name, nat_id, phone, email, address, created_at)
                       VALUES (?,?,?,?,?,?)""",
                    ("Jane Moyo", "63-123456Z63", "0772 000 111",
                     "jane@example.com", "12 West Rd, Ward 16", now))
        owner_id = cur.lastrowid

        cur.execute("""INSERT INTO parcels(parcel_id, pluscode, ward, zone, neighborhood, owner_id, geom_wkt)
                       VALUES (?,?,?,?,?,?,?)""",
                    ("002344-12", "7F25+38", "Ward 16", "Residential", "Central East",
                     owner_id, "POLYGON((0 0,1 0,1 1,0 1,0 0))"))

        cur.execute("""INSERT INTO assessments(parcel_id, method, avm_value_usd, assessed_at)
                       VALUES (?,?,?,?)""",
                    ("002344-12", "GAMA", 125000, now))

        cur.execute("""INSERT INTO tax_bills(parcel_id, period, rate_code, amount_due, status, issued_at, due_at)
                       VALUES (?,?,?,?,?,?,?)""",
                    ("002344-12", "2025-H1", "R1", 1250, "Outstanding", now, "2025-06-30"))

        # sample payment (comment out to keep bill outstanding)
        # cur.execute("""INSERT INTO payments(bill_id, paid_at, amount, channel)
        #                VALUES (1, ?, 500, 'MobileMoney')""", (now,))

    conn.commit()
    conn.close()

if __name__ == "__main__":
    init_db()
    print("Database ready: geotax360.db")